"""Add active column to products

Revision ID: 18560ce0067d
Revises: e47363986910
Create Date: 2025-11-15 00:03:32.269971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18560ce0067d'
down_revision = 'e47363986910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
